joints = {
 "head": 0,
 "right wrist": 10,
 "left wrist": 9,
 "right elbow": 8,
 "left elbow": 7,
 "right shoulder": 6,
 "left shoulder": 5,
 "jaw": 73,

 "left thumb end": 28,
 "left index end": 32,
 "left middle end": 36,
 "left ring end": 40,
 "left little end": 44,

 "left little knuckle": 41,
 "left little joint 1": 42,
 "left little joint 2": 43,
 "left ring knuckle": 37,
 "left ring joint 1": 38,
 "left ring joint 2": 39,
 "left middle knuckle": 33,
 "left middle joint 1": 34,
 "left middle joint 2": 35,
 "left index knuckle": 29,
 "left index joint 1": 30,
 "left index joint 2": 31,
 "left thumb knuckle": 25,
 "left thumb joint 1": 26,
 "left thumb joint 2": 27,

 "right thumb end": 48,
 "right index end": 52,
 "right middle end": 56,
 "right ring end": 60,
 "right little end": 64,

 "right little knuckle": 61,
 "right little joint 1": 62,
 "right little joint 2": 63,
 "right ring knuckle": 57,
 "right ring joint 1": 58,
 "right ring joint 2": 59,
 "right middle knuckle": 53,
 "right middle joint 1": 54,
 "right middle joint 2": 55,
 "right index knuckle": 49,
 "right index joint 1": 50,
 "right index joint 2": 51,
 "right thumb knuckle": 45,
 "right thumb joint 1": 46,
 "right thumb joint 2": 47,

 "right eye": 2,
 "left eye": 1,
 "right ear": 4,
 "left ear": 3,
 }
